package IU;

import java.awt.Color;
import sm.agm.iu.HerramientasDibujo;
import sm.agm.iu.Lienzo2DImagen;

public class VentanaInterna extends javax.swing.JInternalFrame {

    private VentanaPrincipal vp = null;

    public VentanaInterna(VentanaPrincipal ventanaPrincipal, int ancho, int alto) {
        initComponents();

        vp = ventanaPrincipal;
        //ActualizarHerramientasEnVentanaPrincipal();
        
        lienzo2DImagen.setTamanno(ancho, alto);
    }
    
    public void ActualizarHerramientasEnVentanaPrincipal() {
    
        if (lienzo2DImagen.getEnEdicion())
            vp.setHerramienta(HerramientasDibujo.SELECCION);
        else
            vp.setHerramienta(lienzo2DImagen.getHerramienta());
        
        ActualizarPropiedadesEnVentanaPrincipal();
    }
    
    public void ActualizarPropiedadesEnVentanaPrincipal() {
    
        vp.setColorTrazo(lienzo2DImagen.getColorTrazo());
        vp.setColorRelleno(lienzo2DImagen.getColorRelleno());
        vp.setColorDegradado(lienzo2DImagen.getColorDegradado());
        
        vp.setTrazo(lienzo2DImagen.getTrazo());
        vp.setGrosorLinea(lienzo2DImagen.getGrosor());
        
        vp.setRelleno(lienzo2DImagen.getRelleno(), lienzo2DImagen.getDegradado());
        vp.setDireccionDegradado(lienzo2DImagen.getDireccionDegradado());
        
        vp.setTransparencia(lienzo2DImagen.getTransparencia());
        vp.setCantidadTransparecia(lienzo2DImagen.getCantidadTransparencia());
        vp.setAlisar(lienzo2DImagen.getAlisar());
        
        vp.setFuenteTexto (lienzo2DImagen.getFuente());
        vp.setNegrita (lienzo2DImagen.getNegrita());
        vp.setCursiva (lienzo2DImagen.getCursiva());
        vp.setSubrayado (lienzo2DImagen.getSubrayado());
        vp.setTamanoLetra (lienzo2DImagen.getTamanoLetra());
        vp.setText (lienzo2DImagen.getTexto());
    }
    
    public Lienzo2DImagen getLienzo() {
        
        return lienzo2DImagen;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        lienzo2DImagen = new sm.agm.iu.Lienzo2DImagen();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        scrollPane.setBackground(new java.awt.Color(153, 153, 153));
        scrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lienzo2DImagen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lienzo2DImagenMouseMoved(evt);
            }
        });
        lienzo2DImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lienzo2DImagenMouseExited(evt);
            }
        });

        javax.swing.GroupLayout lienzo2DImagenLayout = new javax.swing.GroupLayout(lienzo2DImagen);
        lienzo2DImagen.setLayout(lienzo2DImagenLayout);
        lienzo2DImagenLayout.setHorizontalGroup(
            lienzo2DImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );
        lienzo2DImagenLayout.setVerticalGroup(
            lienzo2DImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        scrollPane.setViewportView(lienzo2DImagen);

        getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        ActualizarHerramientasEnVentanaPrincipal();
    }//GEN-LAST:event_formInternalFrameActivated

    private void lienzo2DImagenMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo2DImagenMouseMoved
        if (getLienzo().getAncho() > evt.getPoint().x && getLienzo().getAlto() > evt.getPoint().y)
            vp.setPosicion(evt.getPoint(), new Color(getLienzo().getImagenCopia().getRGB(evt.getPoint().x, evt.getPoint().y)));
        else
            vp.setPosicion(null, null);
    }//GEN-LAST:event_lienzo2DImagenMouseMoved

    private void lienzo2DImagenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo2DImagenMouseExited
        vp.setPosicion(null, null);
    }//GEN-LAST:event_lienzo2DImagenMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sm.agm.iu.Lienzo2DImagen lienzo2DImagen;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
