package IU;

import java.io.File;
import javax.sound.sampled.LineEvent;
import javax.sound.sampled.LineListener;
import sm.sound.SMRecorder;
import sm.sound.SMSoundRecorder;

public class VentanaInternaGrabacion extends javax.swing.JInternalFrame {

    SMRecorder recorder;
    
    public VentanaInternaGrabacion(File f) {
        
        initComponents();
        
        recorder = new SMSoundRecorder(f);
        
        ((SMSoundRecorder)recorder).addLineListener(new ManejadorAudio());
        
        GrupoReproduccion.add(botonGrabar);
        GrupoReproduccion.add(botonParar);
    }
    
    public void dispose () { 
        if(recorder!=null)
            recorder.stop();
        
        super.dispose ();
    }
    
    class ManejadorAudio implements LineListener {
        @Override
        public void update(LineEvent event) {
            if (event.getType() == LineEvent.Type.START) {}
            if (event.getType() == LineEvent.Type.STOP) {
                botonParar.setSelected(true);
            }
            if (event.getType() == LineEvent.Type.CLOSE) {
                botonParar.setSelected(false);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoReproduccion = new javax.swing.ButtonGroup();
        botonGrabar = new javax.swing.JToggleButton();
        botonParar = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        botonGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/RecordPressed_48x48.png"))); // NOI18N
        botonGrabar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/RecordPressed_48x48.png"))); // NOI18N
        botonGrabar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/RecordDisabled_48x48.png"))); // NOI18N
        botonGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGrabarActionPerformed(evt);
            }
        });
        getContentPane().add(botonGrabar);

        botonParar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/StopNormalRed_48x48.png"))); // NOI18N
        botonParar.setSelected(true);
        botonParar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/StopNormalRed_48x48.png"))); // NOI18N
        botonParar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/StopDisabled_48x48.png"))); // NOI18N
        botonParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPararActionPerformed(evt);
            }
        });
        getContentPane().add(botonParar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGrabarActionPerformed
        if(recorder!=null) recorder.record();
    }//GEN-LAST:event_botonGrabarActionPerformed

    private void botonPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPararActionPerformed
        if(recorder!=null) recorder.stop();
    }//GEN-LAST:event_botonPararActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoReproduccion;
    private javax.swing.JToggleButton botonGrabar;
    private javax.swing.JToggleButton botonParar;
    // End of variables declaration//GEN-END:variables
}
