package IU;

import java.io.File;
import javax.sound.sampled.LineEvent;
import javax.sound.sampled.LineListener;
import sm.sound.SMClipPlayer;
import sm.sound.SMPlayer;

public class VentanaInternaReproducir extends javax.swing.JInternalFrame {

    SMPlayer player;
    
    public VentanaInternaReproducir(File f) {
        
        initComponents();
        
        player = new SMClipPlayer(f);
        
        ((SMClipPlayer)player).addLineListener(new ManejadorAudio());
        
        GrupoReproduccion.add(botonReproducir);
        GrupoReproduccion.add(botonParar);
    }

    class ManejadorAudio implements LineListener {
        @Override
        public void update(LineEvent event) {
            //if (event.getType() == LineEvent.Type.START) {}
            if (event.getType() == LineEvent.Type.STOP) {
                botonParar.setSelected(true);
            }
            if (event.getType() == LineEvent.Type.CLOSE) {
                botonParar.setSelected(false);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoReproduccion = new javax.swing.ButtonGroup();
        botonReproducir = new javax.swing.JToggleButton();
        botonParar = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        botonReproducir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/PlayPressed_48x48.png"))); // NOI18N
        botonReproducir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/PlayPressed_48x48.png"))); // NOI18N
        botonReproducir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/PlayDisabled_48x48.png"))); // NOI18N
        botonReproducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReproducirActionPerformed(evt);
            }
        });
        getContentPane().add(botonReproducir);

        botonParar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/StopNormalRed_48x48.png"))); // NOI18N
        botonParar.setSelected(true);
        botonParar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/StopNormalRed_48x48.png"))); // NOI18N
        botonParar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/StopDisabled_48x48.png"))); // NOI18N
        botonParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPararActionPerformed(evt);
            }
        });
        getContentPane().add(botonParar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonReproducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReproducirActionPerformed
        if(player!=null) player.play();
    }//GEN-LAST:event_botonReproducirActionPerformed

    private void botonPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPararActionPerformed
        if(player!=null) player.stop();
    }//GEN-LAST:event_botonPararActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        if(player!=null) player.stop();
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoReproduccion;
    private javax.swing.JToggleButton botonParar;
    private javax.swing.JToggleButton botonReproducir;
    // End of variables declaration//GEN-END:variables
}
